#!/bin/bash
set -evx
for f in ./*modules*
do
    cd "$f"
    for i in `ls -d */` do 
        git diff
        terraform-docs markdown table --output-file README.md --output-mode inject "${i}";
    done
    for y in $(find . -name '*.tf' -print) do
        git diff
        terraform fmt -write=true "${y}"
    done
    cd ..
done
